//! TD-0001 W2 — differential test oracle (ADR-0003 §3).
//!
//! An **independent** deserializer, generated by `typify` from a byte-pinned provider schema
//! (never the hand-written `parse_*_usage`), parses the same usage objects and recomputes the
//! metrics. Agreement raises confidence for free; divergence flags either provider-spec drift or
//! an extractor bug. The generated code is test-only — it is never linked into the shipped crate
//! or the bindings (ADR-0003 §1/§3).
//!
//! Scope: OpenAI + Anthropic (the two named in ADR-0003 W2 — the cache-split-sensitive pair).
//! Schemas + provenance live in `tests/schemas/`.

use sandhi_providers::{parse_anthropic_usage, parse_openai_usage, ParsedUsage};
use serde_json::Value;

// typify generates `#[derive(Deserialize)]` structs from the byte-pinned schemas at compile time.
// Generated ⇒ suppress the lints generated code trips under `-D warnings` (dead fields, style).
// Each `import_types!` emits its own `error` module, so they live in separate submodules.
#[allow(dead_code, unused, clippy::all, clippy::pedantic)]
mod openai_schema {
    typify::import_types!("tests/schemas/openai_completion_usage.schema.json");
}
#[allow(dead_code, unused, clippy::all, clippy::pedantic)]
mod anthropic_schema {
    typify::import_types!("tests/schemas/anthropic_message_usage.schema.json");
}

fn parse_expected(s: &str) -> ParsedUsage {
    let v: Value = serde_json::from_str(s).unwrap();
    ParsedUsage {
        tokens_in: v["tokens_in"].as_u64().unwrap(),
        tokens_out: v["tokens_out"].as_u64().unwrap(),
        cache_creation_tokens: v["cache_creation_tokens"].as_u64().unwrap(),
        cache_read_tokens: v["cache_read_tokens"].as_u64().unwrap(),
    }
}

/// Recompute `ParsedUsage` from the schema-generated OpenAI struct — an independent path from
/// `parse_openai_usage` (which reads the raw JSON). Same formula (fresh = prompt − cached), but
/// over spec-typed fields: if the parser read a field the spec does not declare, this diverges.
fn oracle_openai(usage: &Value) -> ParsedUsage {
    let u: openai_schema::OpenAiCompletionUsage = serde_json::from_value(usage.clone()).unwrap();
    let cached = u
        .prompt_tokens_details
        .as_ref()
        .map(|d| d.cached_tokens)
        .unwrap_or(0);
    ParsedUsage {
        tokens_in: (u.prompt_tokens - cached).max(0) as u64,
        tokens_out: u.completion_tokens.max(0) as u64,
        cache_creation_tokens: 0,
        cache_read_tokens: cached.max(0) as u64,
    }
}

fn oracle_anthropic(usage: &Value) -> ParsedUsage {
    let u: anthropic_schema::AnthropicMessageUsage = serde_json::from_value(usage.clone()).unwrap();
    ParsedUsage {
        tokens_in: u.input_tokens.max(0) as u64,
        tokens_out: u.output_tokens.max(0) as u64,
        cache_creation_tokens: u.cache_creation_input_tokens.unwrap_or(0).max(0) as u64,
        cache_read_tokens: u.cache_read_input_tokens.unwrap_or(0).max(0) as u64,
    }
}

#[test]
fn openai_shipped_parser_agrees_with_generated_oracle() {
    let resp: Value = serde_json::from_str(include_str!("fixtures/openai/complete.json")).unwrap();
    let expected = parse_expected(include_str!("fixtures/openai/expected_usage.json"));
    let shipped = parse_openai_usage(&resp).expect("usage present");
    let oracle = oracle_openai(&resp["usage"]);
    assert_eq!(
        shipped, oracle,
        "shipped parse_openai_usage vs schema-generated oracle"
    );
    assert_eq!(
        shipped, expected,
        "shipped parse_openai_usage vs ground truth"
    );
}

#[test]
fn anthropic_shipped_parser_agrees_with_generated_oracle() {
    let resp: Value =
        serde_json::from_str(include_str!("fixtures/anthropic/complete_cache_split.json")).unwrap();
    let expected = parse_expected(include_str!("fixtures/anthropic/expected_usage.json"));
    let shipped = parse_anthropic_usage(&resp).expect("usage present");
    let oracle = oracle_anthropic(&resp["usage"]);
    assert_eq!(
        shipped, oracle,
        "shipped parse_anthropic_usage vs schema-generated oracle"
    );
    assert_eq!(
        shipped, expected,
        "shipped parse_anthropic_usage vs ground truth"
    );
}
