"""Exact dependency-bot provenance is distinct from AI authorship attribution."""
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location(
    "attribution_guard", Path(__file__).resolve().parents[2] / "scripts/check_no_agent_attribution.py"
)
assert spec and spec.loader
guard = importlib.util.module_from_spec(spec)
spec.loader.exec_module(guard)

TRAILER = "Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"
PIN_TRAILER = "Co-authored-by: sandhi pin bot <pin-bot@anvai-labs.local>"


class DependencyProvenanceTests(unittest.TestCase):
    def test_official_complete_trailer_is_accepted(self):
        for trailer in (TRAILER, PIN_TRAILER):
            for text in [trailer, "fix(deps): update\n\n" + trailer + "\n", trailer + "\r\n"]:
                with self.subTest(text=text):
                    self.assertEqual(guard.scan(text, "test"), [])
        workflow = (Path(__file__).resolve().parents[2]
                    / ".github/workflows/update-protocol-pin.yml").read_text()
        self.assertIn('git config user.name "sandhi pin bot"', workflow)
        self.assertIn('git config user.email "pin-bot@anvai-labs.local"', workflow)

    def test_changed_or_appended_attribution_is_not_exempt(self):
        for text in [
            TRAILER.replace("49699333", "1"),
            TRAILER.replace("@users.noreply.github.com", "@example.com"),
            TRAILER + " generated by Codex",
            TRAILER.replace("dependabot[bot]", "another[bot]"),
            "Co-authored-by: automation-bot <bot@example.com>",
            "Generated-by: dependabot[bot]",
            PIN_TRAILER.replace("sandhi pin bot", "another pin bot"),
            PIN_TRAILER.replace("pin-bot@", "other-bot@"),
            PIN_TRAILER.replace("@anvai-labs.local", "@example.com"),
            PIN_TRAILER + " generated by Codex",
            PIN_TRAILER + " Co-authored-by: another bot <bot@example.com>",
            "Generated-by: sandhi pin bot",
            PIN_TRAILER.replace("pin-bot@anvai-labs.local", "49699333+dependabot[bot]@users.noreply.github.com"),
            TRAILER.replace("49699333+dependabot[bot]@users.noreply.github.com", "pin-bot@anvai-labs.local"),
        ]:
            with self.subTest(text=text):
                self.assertTrue(guard.scan(text, "test"))

    def test_valid_trailer_does_not_hide_separate_forbidden_lines(self):
        for trailer in (TRAILER, PIN_TRAILER):
            with self.subTest(trailer=trailer):
                self.assertTrue(guard.scan(trailer + "\nGenerated-by: Codex\n", "test"))
        self.assertEqual(guard.scan("Generated-by: victor-code-ai", "test"), [])


if __name__ == "__main__":
    unittest.main()
