"""Exact dependency-bot provenance is distinct from AI authorship attribution."""
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location(
    "attribution_guard", Path(__file__).resolve().parents[2] / "scripts/check_no_agent_attribution.py"
)
assert spec and spec.loader
guard = importlib.util.module_from_spec(spec)
spec.loader.exec_module(guard)

TRAILER = "Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"


class DependencyProvenanceTests(unittest.TestCase):
    def test_official_complete_trailer_is_accepted(self):
        for text in [TRAILER, "fix(deps): update\n\n" + TRAILER + "\n", TRAILER + "\r\n"]:
            with self.subTest(text=text):
                self.assertEqual(guard.scan(text, "test"), [])

    def test_changed_or_appended_attribution_is_not_exempt(self):
        for text in [
            TRAILER.replace("49699333", "1"),
            TRAILER.replace("@users.noreply.github.com", "@example.com"),
            TRAILER + " generated by Codex",
            TRAILER.replace("dependabot[bot]", "another[bot]"),
            "Co-authored-by: automation-bot <bot@example.com>",
            "Generated-by: dependabot[bot]",
        ]:
            with self.subTest(text=text):
                self.assertTrue(guard.scan(text, "test"))

    def test_valid_trailer_does_not_hide_separate_forbidden_lines(self):
        self.assertTrue(guard.scan(TRAILER + "\nGenerated-by: Codex\n", "test"))
        self.assertEqual(guard.scan("Generated-by: victor-code-ai", "test"), [])


if __name__ == "__main__":
    unittest.main()
