# Generated by scripts/gen-binding-contract-facades.py; DO NOT EDIT.
# schema-sha256: 126c95668c4b3c29dc4a8aac0ebb064eb0587512abaa1f3a46fa21d5974acf40
from collections.abc import AsyncIterator
from typing import Any, Literal, NotRequired, TypedDict

JsonValue = Any
Role = Literal["developer", "system", "user", "assistant", "tool", "function"]
FinishReasonV1 = Literal["stop", "length", "tool_calls", "content_filter", "function_call", "unknown"]
UsageCompleteness = Literal["final", "partial", "unavailable"]

class TextPart(TypedDict):
    type: Literal["text"]
    text: str
class ImageUrlPart(TypedDict):
    type: Literal["image_url"]
    image_url: str
    detail: NotRequired[str]
class InputAudioPart(TypedDict):
    type: Literal["input_audio"]
    data: str
    format: str
class FilePart(TypedDict):
    type: Literal["file"]
    file_id: NotRequired[str]
    file_data: NotRequired[str]
    filename: NotRequired[str]
ContentPart = TextPart | ImageUrlPart | InputAudioPart | FilePart
MessageContent = str | list[ContentPart]

class ToolCallV1(TypedDict):
    id: str
    name: str
    arguments: str
    extensions: NotRequired[dict[str, JsonValue]]
class DeveloperMessage(TypedDict):
    role: Literal["developer"]
    content: MessageContent
    name: NotRequired[str]
class SystemMessage(TypedDict):
    role: Literal["system"]
    content: MessageContent
    name: NotRequired[str]
class UserMessage(TypedDict):
    role: Literal["user"]
    content: MessageContent
    name: NotRequired[str]
class AssistantMessage(TypedDict):
    role: Literal["assistant"]
    content: NotRequired[MessageContent]
    name: NotRequired[str]
    tool_calls: NotRequired[list[ToolCallV1]]
    refusal: NotRequired[str]
class ToolMessage(TypedDict):
    role: Literal["tool"]
    content: MessageContent
    tool_call_id: str
class FunctionMessage(TypedDict):
    role: Literal["function"]
    content: MessageContent
    name: str
ChatMessageV1 = DeveloperMessage | SystemMessage | UserMessage | AssistantMessage | ToolMessage | FunctionMessage

class ToolDefinitionV1(TypedDict):
    name: str
    parameters: JsonValue
    description: NotRequired[str]
    strict: NotRequired[bool]
class RequestMetadataV1(TypedDict, total=False):
    session_id: str
    virtual_key_id: str
    subject_id: str
    group_id: str
    route: str
class ChatRequestV1(TypedDict):
    model: str
    messages: list[ChatMessageV1]
    schema_version: NotRequired[Literal["1"]]
    tools: NotRequired[list[ToolDefinitionV1]]
    tool_choice: NotRequired[Literal["none", "auto", "required"] | dict[str, str]]
    temperature: NotRequired[float]
    max_output_tokens: NotRequired[int]
    stop: NotRequired[list[str]]
    response_format: NotRequired[JsonValue]
    seed: NotRequired[int]
    metadata: NotRequired[RequestMetadataV1]
    extensions: NotRequired[dict[str, JsonValue]]
class UsageV2(TypedDict):
    tokens_in: int
    tokens_out: int
    cache_creation_tokens: int
    cache_read_tokens: int
    completeness: NotRequired[UsageCompleteness]
    attempts: NotRequired[int]
    outcome: NotRequired[str]
    upstream_request_id: NotRequired[str]
    audio_input_tokens: NotRequired[int]
    audio_output_tokens: NotRequired[int]
    reasoning_tokens: NotRequired[int]
    accepted_prediction_tokens: NotRequired[int]
    rejected_prediction_tokens: NotRequired[int]
class AssistantOutputV1(TypedDict):
    content: NotRequired[MessageContent]
    tool_calls: NotRequired[list[ToolCallV1]]
    refusal: NotRequired[str]
class ChatResponseV1(TypedDict):
    schema_version: Literal["1"]
    model: str
    output: AssistantOutputV1
    usage: UsageV2
    id: NotRequired[str]
    finish_reason: NotRequired[FinishReasonV1]
    extensions: NotRequired[dict[str, JsonValue]]
class ProviderErrorV1(TypedDict):
    code: str
    message: str
    retryable: bool
    http_status: NotRequired[int]
    provider: NotRequired[str]
    request_id: NotRequired[str]
    details: NotRequired[dict[str, JsonValue]]

ChatStreamEventV1 = dict[str, JsonValue]
ProviderDescriptorV1 = dict[str, JsonValue]

class TypedEventStream(AsyncIterator[str]):
    async def __anext__(self) -> str: ...
class TypedProvider:
    @property
    def provider(self) -> str: ...
    async def complete_json(self, request_json: str) -> str: ...
    def stream_json(self, request_json: str) -> TypedEventStream: ...
class ProviderRuntime:
    def provider(self, provider: str, model: str, api_key: str, *, base_url: str | None = ..., headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ..., auth_scheme: Literal["api_key", "bearer"] | None = ..., protocol: Literal["chat_completions", "responses", "chatgpt_responses"] | None = ...) -> TypedProvider: ...
    def openai_compat(self, provider: str, base_url: str, api_key: str, *, headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ...) -> TypedProvider: ...
    def openai_responses(self, provider: str, base_url: str, bearer_token: str, *, headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ...) -> TypedProvider: ...

def provider_spec(provider: str, model: str | None = ...) -> dict[str, JsonValue]: ...
def provider_descriptor_json(provider: str) -> str: ...
def chat_contract_schema_json(name: str) -> str: ...
def wire_contract_version() -> str: ...
