// Generated by scripts/gen-binding-contract-facades.py; DO NOT EDIT.
// schema-sha256: 0808e1b284679f40491843e2e0a2446969493c8a1c57e2b3123ca9230992b3d8
export type JsonValue = unknown
export type Role = "developer" | "system" | "user" | "assistant" | "tool" | "function"
export type FinishReasonV1 = "stop" | "length" | "tool_calls" | "content_filter" | "function_call" | "unknown"
export type UsageCompleteness = "final" | "partial" | "unavailable"
export type UsageBasis = "provider_reported" | "estimated"
export type LatencySource = "origin" | "boundary"
export type CacheReadStatus = "reported" | "absent" | "malformed" | "unsupported"
export type CacheReadSource = "origin_usage" | "caller_supplied" | "explicit_capability"
export interface CacheReadObservation { status: CacheReadStatus; source: CacheReadSource }
export interface CacheReadCoverage { reported: number; absent: number; malformed: number; unsupported: number; unknown: number }
export type ContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: string; detail?: string }
  | { type: "input_audio"; data: string; format: string }
  | { type: "file"; file_id?: string; file_data?: string; filename?: string }
export type MessageContent = string | ContentPart[]
export interface ToolCallV1 { id: string; name: string; arguments: string; extensions?: Record<string, JsonValue> }
export type ChatMessageV1 =
  | { role: "developer" | "system" | "user"; content: MessageContent; name?: string }
  | { role: "assistant"; content?: MessageContent; name?: string; tool_calls?: ToolCallV1[]; refusal?: string }
  | { role: "tool"; content: MessageContent; tool_call_id: string }
  | { role: "function"; content: MessageContent; name: string }
export interface ToolDefinitionV1 { name: string; parameters: JsonValue; description?: string; strict?: boolean }
export interface RequestMetadataV1 { session_id?: string; virtual_key_id?: string; subject_id?: string; group_id?: string; route?: string }
export interface ThinkingV1 { enabled: boolean; budget_tokens?: number }
export interface ChatRequestV1 {
  schema_version?: "1"; model: string; messages: ChatMessageV1[]; tools?: ToolDefinitionV1[]
  tool_choice?: "none" | "auto" | "required" | { name: string }; temperature?: number
  max_output_tokens?: number; stop?: string[]; response_format?: JsonValue; seed?: number
  metadata?: RequestMetadataV1; reasoning_effort?: string; thinking?: ThinkingV1
  include_native_response?: boolean
  extensions?: Record<string, JsonValue>
}
export interface UsageV2 {
  tokens_in: number; tokens_out: number; cache_creation_tokens: number; cache_read_tokens: number
  cache_read_observation?: CacheReadObservation
  completeness?: UsageCompleteness; basis?: UsageBasis; attempts?: number; outcome?: string
  upstream_request_id?: string
  duration_ms?: number; duration_source?: LatencySource
  time_to_first_token_ms?: number; time_to_first_token_source?: LatencySource
  audio_input_tokens?: number; audio_output_tokens?: number; reasoning_tokens?: number
  reasoning_included?: boolean
  accepted_prediction_tokens?: number; rejected_prediction_tokens?: number
}
export interface PolicySelectorV1 { issuer?: string | null; subjects?: string[]; groups?: string[]; roles?: string[]; upstreams?: string[]; models?: string[] }
export type PolicyEvaluatorV1 =
  | { kind: "regex"; pattern: string }
  | { kind: "threshold"; metric: "body_bytes" | "max_output_tokens"; above: number }
  | { kind: "lexical_similarity"; reference: string; at_least: number }
  | { kind: "registered"; name: string; configuration: JsonValue }
export interface PolicyRuleV1 { id: string; when?: PolicySelectorV1; evaluator: PolicyEvaluatorV1; effect: "audit" | "quarantine" | "block" }
export interface PolicyDocumentV1 { schema_version: "1"; revision: number; deadline_ms: number; max_body_bytes: number; rules: PolicyRuleV1[] }
export interface PolicyDecisionV1 { revision: number; disposition: "forward" | "quarantine" | "block" | "unavailable"; matched_rules: string[]; reason: string; elapsed_us: number }
export interface LatencySummary { samples: number; p50_ms: number; p95_ms: number; ttft_p50_ms?: number }
export interface UsageAggregateV1 {
  key: string; calls: number; tokens_in: number; tokens_out: number;
  cache_creation_tokens: number; cache_read_tokens: number; reasoning_tokens: number;
  cache_read_coverage?: CacheReadCoverage
  billable_tokens: number; latency?: LatencySummary
}
export interface AssistantOutputV1 { content?: MessageContent; tool_calls?: ToolCallV1[]; refusal?: string }
export interface ChatResponseV1 {
  schema_version: "1"; id?: string; model: string; output: AssistantOutputV1
  finish_reason?: FinishReasonV1; usage: UsageV2; extensions?: Record<string, JsonValue>
}
export interface ProviderErrorV1 { code: string; message: string; retryable: boolean; http_status?: number; provider?: string; request_id?: string; details?: Record<string, JsonValue> }
export type ChatStreamEventV1 =
  | { event: "response_start"; id?: string; model: string }
  | { event: "text_delta" | "reasoning_delta" | "refusal_delta"; delta: string }
  | { event: "tool_call_start"; index: number; id: string; name: string }
  | { event: "tool_call_arguments_delta"; index: number; delta: string }
  | { event: "tool_call_end"; index: number }
  | { event: "usage"; usage: UsageV2 }
  | { event: "finish"; reason: FinishReasonV1 }
  | { event: "error"; error: ProviderErrorV1 }
export interface ProviderDescriptorV1 {
  schema_version: "1"; slug: string; aliases?: string[]; endpoint_family: string; base_url: string
  capabilities: Record<string, boolean>; models?: JsonValue[]; extensions?: Record<string, JsonValue>
}
