// Generated by scripts/gen-binding-contract-facades.py; DO NOT EDIT.
// schema-sha256: 35958c19ff9d89e4ac7541785108ad02f234ce984f9b75018e6e00951e30cddc
export type JsonValue = unknown
export type Role = "developer" | "system" | "user" | "assistant" | "tool" | "function"
export type FinishReasonV1 = "stop" | "length" | "tool_calls" | "content_filter" | "function_call" | "unknown"
export type UsageCompleteness = "final" | "partial" | "unavailable"
export type ContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: string; detail?: string }
  | { type: "input_audio"; data: string; format: string }
  | { type: "file"; file_id?: string; file_data?: string; filename?: string }
export type MessageContent = string | ContentPart[]
export interface ToolCallV1 { id: string; name: string; arguments: string; extensions?: Record<string, JsonValue> }
export type ChatMessageV1 =
  | { role: "developer" | "system" | "user"; content: MessageContent; name?: string }
  | { role: "assistant"; content?: MessageContent; name?: string; tool_calls?: ToolCallV1[]; refusal?: string }
  | { role: "tool"; content: MessageContent; tool_call_id: string }
  | { role: "function"; content: MessageContent; name: string }
export interface ToolDefinitionV1 { name: string; parameters: JsonValue; description?: string; strict?: boolean }
export interface RequestMetadataV1 { session_id?: string; virtual_key_id?: string; subject_id?: string; group_id?: string; route?: string }
export interface ChatRequestV1 {
  schema_version?: "1"; model: string; messages: ChatMessageV1[]; tools?: ToolDefinitionV1[]
  tool_choice?: "none" | "auto" | "required" | { name: string }; temperature?: number
  max_output_tokens?: number; stop?: string[]; response_format?: JsonValue; seed?: number
  metadata?: RequestMetadataV1; extensions?: Record<string, JsonValue>
}
export interface UsageV2 {
  tokens_in: number; tokens_out: number; cache_creation_tokens: number; cache_read_tokens: number
  completeness?: UsageCompleteness; attempts?: number; outcome?: string; upstream_request_id?: string
  audio_input_tokens?: number; audio_output_tokens?: number; reasoning_tokens?: number
  accepted_prediction_tokens?: number; rejected_prediction_tokens?: number
}
export interface AssistantOutputV1 { content?: MessageContent; tool_calls?: ToolCallV1[]; refusal?: string }
export interface ChatResponseV1 {
  schema_version: "1"; id?: string; model: string; output: AssistantOutputV1
  finish_reason?: FinishReasonV1; usage: UsageV2; extensions?: Record<string, JsonValue>
}
export interface ProviderErrorV1 { code: string; message: string; retryable: boolean; http_status?: number; provider?: string; request_id?: string; details?: Record<string, JsonValue> }
export type ChatStreamEventV1 =
  | { event: "response_start"; id?: string; model: string }
  | { event: "text_delta" | "reasoning_delta" | "refusal_delta"; delta: string }
  | { event: "tool_call_start"; index: number; id: string; name: string }
  | { event: "tool_call_arguments_delta"; index: number; delta: string }
  | { event: "tool_call_end"; index: number }
  | { event: "usage"; usage: UsageV2 }
  | { event: "finish"; reason: FinishReasonV1 }
  | { event: "error"; error: ProviderErrorV1 }
export interface ProviderDescriptorV1 {
  schema_version: "1"; slug: string; aliases?: string[]; endpoint_family: string; base_url: string
  capabilities: Record<string, boolean>; models?: JsonValue[]; extensions?: Record<string, JsonValue>
}
