// Sandhi Node entry point (ADR-0047 D10 step 3c).
//
// Re-exports the napi-generated binding (`index.js`) and adds the one thing the Rust addon can't
// declare itself: a `Symbol.asyncIterator` on `ByteStream`, so a streaming transport call is usable
// with `for await`. `ByteStream.read()` resolves to the next chunk, or `null` when exhausted.
//
// This file is hand-written and stable; `index.js` / `index.d.ts` are regenerated by `napi build`.
// The named re-exports below are literal (not `module.exports = native`) so ESM consumers can do
// `import { complete } from "@anvai-labs/sandhi"` — cjs-module-lexer only sees literal assignments.
// Keep this list in sync with `index.js` when the addon gains a new export.

const native = require("./index.js");

if (native.ByteStream && !native.ByteStream.prototype[Symbol.asyncIterator]) {
  native.ByteStream.prototype[Symbol.asyncIterator] = function asyncIterator() {
    const stream = this;
    return {
      async next() {
        const chunk = await stream.read();
        return chunk === null || chunk === undefined
          ? { done: true, value: undefined }
          : { done: false, value: chunk };
      },
    };
  };
}

module.exports.wireContractVersion = native.wireContractVersion;
module.exports.parseUsage = native.parseUsage;
module.exports.Gateway = native.Gateway;
module.exports.complete = native.complete;
module.exports.stream = native.stream;
module.exports.registerProvider = native.registerProvider;
module.exports.ByteStream = native.ByteStream;
