#!/usr/bin/env python3
"""Generate checked Python/TypeScript facades for Sandhi's versioned JSON contract.

Rust + schemars remain authoritative. The digest embedded in each facade makes schema drift a
release-gate failure; update the narrow language templates only when the canonical contract does.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = (
    "chat-request.v1.schema.json",
    "chat-response.v1.schema.json",
    "chat-stream-event.v1.schema.json",
    "provider-descriptor.v1.schema.json",
    "provider-error.v1.schema.json",
    "usage.v2.schema.json",
)


def schema_digest() -> str:
    digest = hashlib.sha256()
    for name in SCHEMAS:
        digest.update(name.encode())
        digest.update((ROOT / "schemas" / name).read_bytes())
    return digest.hexdigest()


def python_facade(digest: str) -> str:
    return f'''# Generated by scripts/gen-binding-contract-facades.py; DO NOT EDIT.
# schema-sha256: {digest}
from collections.abc import AsyncIterator
from typing import Any, Literal, NotRequired, TypedDict

JsonValue = Any
Role = Literal["developer", "system", "user", "assistant", "tool", "function"]
FinishReasonV1 = Literal["stop", "length", "tool_calls", "content_filter", "function_call", "unknown"]
UsageCompleteness = Literal["final", "partial", "unavailable"]

class TextPart(TypedDict):
    type: Literal["text"]
    text: str
class ImageUrlPart(TypedDict):
    type: Literal["image_url"]
    image_url: str
    detail: NotRequired[str]
class InputAudioPart(TypedDict):
    type: Literal["input_audio"]
    data: str
    format: str
class FilePart(TypedDict):
    type: Literal["file"]
    file_id: NotRequired[str]
    file_data: NotRequired[str]
    filename: NotRequired[str]
ContentPart = TextPart | ImageUrlPart | InputAudioPart | FilePart
MessageContent = str | list[ContentPart]

class ToolCallV1(TypedDict):
    id: str
    name: str
    arguments: str
    extensions: NotRequired[dict[str, JsonValue]]
class DeveloperMessage(TypedDict):
    role: Literal["developer"]
    content: MessageContent
    name: NotRequired[str]
class SystemMessage(TypedDict):
    role: Literal["system"]
    content: MessageContent
    name: NotRequired[str]
class UserMessage(TypedDict):
    role: Literal["user"]
    content: MessageContent
    name: NotRequired[str]
class AssistantMessage(TypedDict):
    role: Literal["assistant"]
    content: NotRequired[MessageContent]
    name: NotRequired[str]
    tool_calls: NotRequired[list[ToolCallV1]]
    refusal: NotRequired[str]
class ToolMessage(TypedDict):
    role: Literal["tool"]
    content: MessageContent
    tool_call_id: str
class FunctionMessage(TypedDict):
    role: Literal["function"]
    content: MessageContent
    name: str
ChatMessageV1 = DeveloperMessage | SystemMessage | UserMessage | AssistantMessage | ToolMessage | FunctionMessage

class ToolDefinitionV1(TypedDict):
    name: str
    parameters: JsonValue
    description: NotRequired[str]
    strict: NotRequired[bool]
class RequestMetadataV1(TypedDict, total=False):
    session_id: str
    virtual_key_id: str
    subject_id: str
    group_id: str
    route: str
class ChatRequestV1(TypedDict):
    model: str
    messages: list[ChatMessageV1]
    schema_version: NotRequired[Literal["1"]]
    tools: NotRequired[list[ToolDefinitionV1]]
    tool_choice: NotRequired[Literal["none", "auto", "required"] | dict[str, str]]
    temperature: NotRequired[float]
    max_output_tokens: NotRequired[int]
    stop: NotRequired[list[str]]
    response_format: NotRequired[JsonValue]
    seed: NotRequired[int]
    metadata: NotRequired[RequestMetadataV1]
    extensions: NotRequired[dict[str, JsonValue]]
class UsageV2(TypedDict):
    tokens_in: int
    tokens_out: int
    cache_creation_tokens: int
    cache_read_tokens: int
    completeness: NotRequired[UsageCompleteness]
    attempts: NotRequired[int]
    outcome: NotRequired[str]
    upstream_request_id: NotRequired[str]
    audio_input_tokens: NotRequired[int]
    audio_output_tokens: NotRequired[int]
    reasoning_tokens: NotRequired[int]
    accepted_prediction_tokens: NotRequired[int]
    rejected_prediction_tokens: NotRequired[int]
class AssistantOutputV1(TypedDict):
    content: NotRequired[MessageContent]
    tool_calls: NotRequired[list[ToolCallV1]]
    refusal: NotRequired[str]
class ChatResponseV1(TypedDict):
    schema_version: Literal["1"]
    model: str
    output: AssistantOutputV1
    usage: UsageV2
    id: NotRequired[str]
    finish_reason: NotRequired[FinishReasonV1]
    extensions: NotRequired[dict[str, JsonValue]]
class ProviderErrorV1(TypedDict):
    code: str
    message: str
    retryable: bool
    http_status: NotRequired[int]
    provider: NotRequired[str]
    request_id: NotRequired[str]
    details: NotRequired[dict[str, JsonValue]]

ChatStreamEventV1 = dict[str, JsonValue]
ProviderDescriptorV1 = dict[str, JsonValue]

class TypedEventStream(AsyncIterator[str]):
    async def __anext__(self) -> str: ...
class TypedProvider:
    @property
    def provider(self) -> str: ...
    async def complete_json(self, request_json: str) -> str: ...
    def stream_json(self, request_json: str) -> TypedEventStream: ...
class ProviderRuntime:
    def provider(self, provider: str, model: str, api_key: str, *, base_url: str | None = ..., headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ..., auth_scheme: Literal["api_key", "bearer"] | None = ..., protocol: Literal["chat_completions", "responses", "chatgpt_responses"] | None = ...) -> TypedProvider: ...
    def openai_compat(self, provider: str, base_url: str, api_key: str, *, headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ...) -> TypedProvider: ...
    def openai_responses(self, provider: str, base_url: str, bearer_token: str, *, headers_json: str | None = ..., max_retries: int | None = ..., timeout_secs: float | None = ..., stream_idle_timeout_secs: float | None = ...) -> TypedProvider: ...

def provider_spec(provider: str, model: str | None = ...) -> dict[str, JsonValue]: ...
def provider_descriptor_json(provider: str) -> str: ...
def chat_contract_schema_json(name: str) -> str: ...
def wire_contract_version() -> str: ...
'''


def typescript_facade(digest: str) -> str:
    return f'''// Generated by scripts/gen-binding-contract-facades.py; DO NOT EDIT.
// schema-sha256: {digest}
export type JsonValue = unknown
export type Role = "developer" | "system" | "user" | "assistant" | "tool" | "function"
export type FinishReasonV1 = "stop" | "length" | "tool_calls" | "content_filter" | "function_call" | "unknown"
export type UsageCompleteness = "final" | "partial" | "unavailable"
export type ContentPart =
  | {{ type: "text"; text: string }}
  | {{ type: "image_url"; image_url: string; detail?: string }}
  | {{ type: "input_audio"; data: string; format: string }}
  | {{ type: "file"; file_id?: string; file_data?: string; filename?: string }}
export type MessageContent = string | ContentPart[]
export interface ToolCallV1 {{ id: string; name: string; arguments: string; extensions?: Record<string, JsonValue> }}
export type ChatMessageV1 =
  | {{ role: "developer" | "system" | "user"; content: MessageContent; name?: string }}
  | {{ role: "assistant"; content?: MessageContent; name?: string; tool_calls?: ToolCallV1[]; refusal?: string }}
  | {{ role: "tool"; content: MessageContent; tool_call_id: string }}
  | {{ role: "function"; content: MessageContent; name: string }}
export interface ToolDefinitionV1 {{ name: string; parameters: JsonValue; description?: string; strict?: boolean }}
export interface RequestMetadataV1 {{ session_id?: string; virtual_key_id?: string; subject_id?: string; group_id?: string; route?: string }}
export interface ChatRequestV1 {{
  schema_version?: "1"; model: string; messages: ChatMessageV1[]; tools?: ToolDefinitionV1[]
  tool_choice?: "none" | "auto" | "required" | {{ name: string }}; temperature?: number
  max_output_tokens?: number; stop?: string[]; response_format?: JsonValue; seed?: number
  metadata?: RequestMetadataV1; extensions?: Record<string, JsonValue>
}}
export interface UsageV2 {{
  tokens_in: number; tokens_out: number; cache_creation_tokens: number; cache_read_tokens: number
  completeness?: UsageCompleteness; attempts?: number; outcome?: string; upstream_request_id?: string
  audio_input_tokens?: number; audio_output_tokens?: number; reasoning_tokens?: number
  accepted_prediction_tokens?: number; rejected_prediction_tokens?: number
}}
export interface AssistantOutputV1 {{ content?: MessageContent; tool_calls?: ToolCallV1[]; refusal?: string }}
export interface ChatResponseV1 {{
  schema_version: "1"; id?: string; model: string; output: AssistantOutputV1
  finish_reason?: FinishReasonV1; usage: UsageV2; extensions?: Record<string, JsonValue>
}}
export interface ProviderErrorV1 {{ code: string; message: string; retryable: boolean; http_status?: number; provider?: string; request_id?: string; details?: Record<string, JsonValue> }}
export type ChatStreamEventV1 =
  | {{ event: "response_start"; id?: string; model: string }}
  | {{ event: "text_delta" | "reasoning_delta" | "refusal_delta"; delta: string }}
  | {{ event: "tool_call_start"; index: number; id: string; name: string }}
  | {{ event: "tool_call_arguments_delta"; index: number; delta: string }}
  | {{ event: "tool_call_end"; index: number }}
  | {{ event: "usage"; usage: UsageV2 }}
  | {{ event: "finish"; reason: FinishReasonV1 }}
  | {{ event: "error"; error: ProviderErrorV1 }}
export interface ProviderDescriptorV1 {{
  schema_version: "1"; slug: string; aliases?: string[]; endpoint_family: string; base_url: string
  capabilities: Record<string, boolean>; models?: JsonValue[]; extensions?: Record<string, JsonValue>
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    digest = schema_digest()
    outputs = {
        ROOT / "bindings/python/sandhi_gateway.pyi": python_facade(digest),
        ROOT / "bindings/node/contracts.d.ts": typescript_facade(digest),
    }
    stale = []
    for path, expected in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(expected)
    if stale:
        raise SystemExit("stale generated contract facades: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
